package com.yz.springboot.mapper;

import com.yz.springboot.entity.Car;

import java.util.List;

/**
 * @author huiRan
 * @date 2018/9/11
 */
public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    int insertSelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    Car selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    int updateByPrimaryKeySelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    int updateByPrimaryKey(Car record);

    /**
     * 批量插入
     */
    void batchInsert(List<Car> list);
}