package com.yz.springboot.entity;

public class Car {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.letter
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.brand
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.vendor
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.name
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.style
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.specifications
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.countries
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String countries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.technology
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String technology;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.level
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.displacement
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private Integer displacement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.transmission
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    private String transmission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.letter
     *
     * @return the value of car.letter
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getLetter() {
        return letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.letter
     *
     * @param letter the value for car.letter
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setLetter(String letter) {
        this.letter = letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.brand
     *
     * @return the value of car.brand
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.brand
     *
     * @param brand the value for car.brand
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.vendor
     *
     * @return the value of car.vendor
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.vendor
     *
     * @param vendor the value for car.vendor
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.name
     *
     * @return the value of car.name
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.name
     *
     * @param name the value for car.name
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.style
     *
     * @return the value of car.style
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.style
     *
     * @param style the value for car.style
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setStyle(String style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.specifications
     *
     * @return the value of car.specifications
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.specifications
     *
     * @param specifications the value for car.specifications
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.countries
     *
     * @return the value of car.countries
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getCountries() {
        return countries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.countries
     *
     * @param countries the value for car.countries
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setCountries(String countries) {
        this.countries = countries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.technology
     *
     * @return the value of car.technology
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.technology
     *
     * @param technology the value for car.technology
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setTechnology(String technology) {
        this.technology = technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.level
     *
     * @return the value of car.level
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.level
     *
     * @param level the value for car.level
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.displacement
     *
     * @return the value of car.displacement
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public Integer getDisplacement() {
        return displacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.displacement
     *
     * @param displacement the value for car.displacement
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setDisplacement(Integer displacement) {
        this.displacement = displacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.transmission
     *
     * @return the value of car.transmission
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public String getTransmission() {
        return transmission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.transmission
     *
     * @param transmission the value for car.transmission
     *
     * @mbggenerated Mon Sep 10 14:11:19 CST 2018
     */
    public void setTransmission(String transmission) {
        this.transmission = transmission;
    }
}